name: Check latest dependencies

on:
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

env: 
  CARGO_TERM_COLOR: always

jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose